-- RUN ONLY in a NEW Supabase project created for this new website.
create extension if not exists pgcrypto;
create table if not exists public.products(id uuid primary key default gen_random_uuid(),network text not null check(network in('RuPay','Visa','Mastercard','American Express')),title text not null,price numeric(12,2) not null check(price>0),card_type text default '',region text default '',availability text default 'AVAILABLE',description text default '',active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,product_id uuid references public.products(id) on delete set null,product_name text not null,amount numeric(12,2) not null check(amount>0),currency text not null default 'INR' check(currency='INR'),customer_email text not null,utr text not null,screenshot_path text not null,status text not null default 'pending' check(status in('pending','approved','rejected')),created_at timestamptz not null default now());
alter table public.products enable row level security;alter table public.orders enable row level security;
drop policy if exists products_read on public.products;create policy products_read on public.products for select using(active=true or lower(coalesce(auth.jwt()->>'email',''))='virexabusiness143@gmail.com');
drop policy if exists products_admin_all on public.products;create policy products_admin_all on public.products for all using(lower(coalesce(auth.jwt()->>'email',''))='virexabusiness143@gmail.com') with check(lower(coalesce(auth.jwt()->>'email',''))='virexabusiness143@gmail.com');
drop policy if exists orders_read on public.orders;create policy orders_read on public.orders for select using(auth.uid()=user_id or lower(coalesce(auth.jwt()->>'email',''))='virexabusiness143@gmail.com');
drop policy if exists orders_insert on public.orders;create policy orders_insert on public.orders for insert with check(auth.uid()=user_id and status='pending' and currency='INR');
drop policy if exists orders_admin_update on public.orders;create policy orders_admin_update on public.orders for update using(lower(coalesce(auth.jwt()->>'email',''))='virexabusiness143@gmail.com') with check(lower(coalesce(auth.jwt()->>'email',''))='virexabusiness143@gmail.com');
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('payment-screenshots','payment-screenshots',false,5242880,array['image/png','image/jpeg','image/webp']) on conflict(id) do update set public=false,file_size_limit=5242880,allowed_mime_types=array['image/png','image/jpeg','image/webp'];
drop policy if exists screenshot_upload_own on storage.objects;create policy screenshot_upload_own on storage.objects for insert to authenticated with check(bucket_id='payment-screenshots' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists screenshot_read_own_admin on storage.objects;create policy screenshot_read_own_admin on storage.objects for select to authenticated using(bucket_id='payment-screenshots' and ((storage.foldername(name))[1]=auth.uid()::text or lower(coalesce(auth.jwt()->>'email',''))='virexabusiness143@gmail.com'));
